export const toppingTypesData = [
  {
    toppingTypeId: 0,
    toppingTypeCategory: "fruits",
    toppingTypeName: "banana",
    frozenImg: "/src/assets/toppings/ice_banana.svg",
    defrostedImg: "/src/assets/toppings/banana.svg",
  },
  {
    toppingTypeId: 1,
    toppingTypeCategory: "fruits",
    toppingTypeName: "cherry",
    frozenImg: "/src/assets/toppings/ice_cherry.svg",
    defrostedImg: "/src/assets/toppings/cherry.svg",
  },
  {
    toppingTypeId: 2,
    toppingTypeCategory: "fruits",
    toppingTypeName: "kiwi",
    frozenImg: "/src/assets/toppings/ice_kiwi.svg",
    defrostedImg: "/src/assets/toppings/kiwi.svg",
  },
  {
    toppingTypeId: 3,
    toppingTypeCategory: "fruits",
    toppingTypeName: "mango",
    frozenImg: "/src/assets/toppings/ice_mango.svg",
    defrostedImg: "/src/assets/toppings/mango.svg",
  },
  {
    toppingTypeId: 4,
    toppingTypeCategory: "fruits",
    toppingTypeName: "shine",
    frozenImg: "/src/assets/toppings/ice_shine.svg",
    defrostedImg: "/src/assets/toppings/shine.svg",
  },
  {
    toppingTypeId: 5,
    toppingTypeCategory: "fruits",
    toppingTypeName: "strawberry",
    frozenImg: "/src/assets/toppings/ice_strawberry.svg",
    defrostedImg: "/src/assets/toppings/strawberry.svg",
  },
  {
    toppingTypeId: 6,
    toppingTypeCategory: "snacks",
    toppingTypeName: "chex",
    frozenImg: "/src/assets/toppings/ice_chex.svg",
    defrostedImg: "/src/assets/toppings/chex.svg",
  },
  {
    toppingTypeId: 7,
    toppingTypeCategory: "snacks",
    toppingTypeName: "maltesers",
    frozenImg: "/src/assets/toppings/ice_maltesers.svg",
    defrostedImg: "/src/assets/toppings/maltesers.svg",
  },
  {
    toppingTypeId: 8,
    toppingTypeCategory: "snacks",
    toppingTypeName: "marshmallow",
    frozenImg: "/src/assets/toppings/ice_marshmallow.svg",
    defrostedImg: "/src/assets/toppings/marshmallow.svg",
  },
  {
    toppingTypeId: 9,
    toppingTypeCategory: "snacks",
    toppingTypeName: "oreo",
    frozenImg: "/src/assets/toppings/ice_oreo.svg",
    defrostedImg: "/src/assets/toppings/oreo.svg",
  },
  {
    toppingTypeId: 10,
    toppingTypeCategory: "snacks",
    toppingTypeName: "stick",
    frozenImg: "/src/assets/toppings/ice_stick.svg",
    defrostedImg: "/src/assets/toppings/stick.svg",
  },
  {
    toppingTypeId: 11,
    toppingTypeCategory: "ricecakes",
    toppingTypeName: "injeolmi",
    frozenImg: "/src/assets/toppings/ice_injeolmi.svg",
    defrostedImg: "/src/assets/toppings/injeolmi.svg",
  },
  {
    toppingTypeId: 12,
    toppingTypeCategory: "ricecakes",
    toppingTypeName: "mochi",
    frozenImg: "/src/assets/toppings/ice_mochi.svg",
    defrostedImg: "/src/assets/toppings/mochi.svg",
  }
];
